/**
 * @vestara/tools-browser — governed browser / computer-use tools for the Agent
 * Harness Tool Runtime.
 */

export {
  abortError,
  type BrowserDriver,
  type BrowserElementRef,
  type BrowserNavigationResult,
  type BrowserObserveResult,
  BrowserObserver,
  type BrowserPoint,
  type BrowserReplayDescriptor,
  type BrowserReplayStep,
  type BrowserScreenshotResult,
  BrowserSession,
  type BrowserSessionOptions,
  type BrowserSnapshotResult,
  type EvidenceGovernance,
  type InformationClassification,
  type InformationRiskLevel,
  informationRiskFor,
  isAbortError,
  isInformationClassification,
  isRedactionMode,
  normalizeOrigin,
  type OriginPolicy,
  originMatches,
  PlaywrightBrowserDriver,
  type RedactionMode,
  type RedactionStatus,
  type ResolvedPolicy,
  redactText,
  resolveBrowserUrl,
  resolveElementToLocator,
  sessionKey,
} from './session';
export {
  addBrowserStep,
  type BrowserStep,
  type BrowserStepAction,
  type BrowserStepStatus,
  type BrowserTask,
  type BrowserTaskStatus,
  completeStep,
  completeTask,
  createBrowserTask,
  failStep,
  failTask,
  startStep,
  startTask,
  summarizeTask,
} from './task';
export {
  BrowserBackTool,
  BrowserClickTool,
  BrowserCloseTool,
  BrowserForwardTool,
  BrowserNavigateTool,
  BrowserObserveTool,
  BrowserReloadTool,
  type BrowserScreenshotOutput,
  BrowserScreenshotTool,
  BrowserScrollTool,
  BrowserSnapshotTool,
  BrowserTypeTool,
  BrowserWaitTool,
} from './tools';
