#!/usr/bin/env tsx
/**
 * Generate internal TypeScript contracts from the pinned OpenCode OpenAPI
 * schema. Output lives in src/generated/ and is private to
 * @vestara/opencode-runtime — it is never exported to Vestara domain or UI
 * layers.
 *
 *   pnpm opencode:spec:generate [--schema <path>]
 *
 * Generation strategy:
 *   - Each component schema becomes a TypeScript interface.
 *   - `object` schemas without properties become index-signature records.
 *   - enum fields become a `Known... | unknown:${string}` union so additive
 *     upstream enum values degrade gracefully instead of crashing parsers.
 *   - $ref targets become their interface name.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(__dirname, '..');
const schemaPath = resolve(
  root,
  process.argv.includes('--schema')
    ? (process.argv[process.argv.indexOf('--schema') + 1] ?? 'openapi/opencode.openapi.json')
    : 'openapi/opencode.openapi.json',
);

function pascalCase(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9]+(.)/g, (_match, chr: string) => chr.toUpperCase())
    .replace(/^./, (chr) => chr.toUpperCase());
}

function sanitize(name: string): string {
  return name.replace(/[^a-zA-Z0-9_$]/g, '');
}

/** Map an OpenAPI schema name to its generated TypeScript interface name. */
function typeNameFor(schemaName: string): string {
  return sanitize(pascalCase(schemaName));
}

function tsTypeFor(schema: Record<string, unknown>, seen: Set<string>): string {
  if (schema.$ref) {
    const refName = String(schema.$ref).split('/').pop() ?? 'unknown';
    return typeNameFor(refName);
  }
  if (schema.oneOf) {
    return (schema.oneOf as unknown[]).map((item) => tsTypeFor(item as Record<string, unknown>, seen)).join(' | ');
  }
  if (schema.anyOf) {
    return (schema.anyOf as unknown[]).map((item) => tsTypeFor(item as Record<string, unknown>, seen)).join(' | ');
  }
  const type = schema.type;
  if (type === 'array') {
    const item = schema.items ? tsTypeFor(schema.items as Record<string, unknown>, seen) : 'unknown';
    return `${item}[]`;
  }
  if (type === 'object' || (!type && schema.properties)) {
    if (schema.additionalProperties === true || (!schema.properties && schema.additionalProperties)) {
      const value =
        schema.additionalProperties && typeof schema.additionalProperties === 'object'
          ? tsTypeFor(schema.additionalProperties as Record<string, unknown>, seen)
          : 'unknown';
      return `Record<string, ${value}>`;
    }
    const props = (schema.properties ?? {}) as Record<string, unknown>;
    if (Object.keys(props).length === 0 && !Array.isArray(schema.required)) {
      return 'Record<string, unknown>';
    }
    const lines = Object.entries(props).map(([name, propSchema]) => {
      const prop = propSchema as Record<string, unknown>;
      const propName = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
      const required = Array.isArray(schema.required) && schema.required.includes(name);
      const typeStr = tsTypeFor(prop, seen);
      return `  readonly ${propName}${required ? '' : '?'}: ${typeStr};`;
    });
    return `{\n${lines.join('\n')}\n}`;
  }
  if (Array.isArray(schema.enum)) {
    // Enum evolution tolerance: known values plus a safe `unknown:` escape.
    const known = schema.enum.map((value) => JSON.stringify(String(value))).join(' | ');
    return `${known} | \`unknown:${'${string}'}\``;
  }
  switch (type) {
    case 'string':
      return 'string';
    case 'number':
      return 'number';
    case 'integer':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'null':
      return 'null';
    default:
      return 'unknown';
  }
}

function generateSchemaInterfaces(document: Record<string, unknown>): string {
  const schemas = ((document.components as Record<string, unknown> | undefined)?.schemas ?? {}) as Record<
    string,
    unknown
  >;
  const chunks: string[] = ['// Generated by opencode:spec:generate — DO NOT EDIT BY HAND.', ''];
  const seen = new Set<string>();
  for (const [name, schema] of Object.entries(schemas)) {
    const interfaceName = typeNameFor(name);
    if (seen.has(interfaceName)) continue;
    seen.add(interfaceName);
    const type = (schema as Record<string, unknown>).type;
    if (type === 'object' || (!type && (schema as Record<string, unknown>).properties)) {
      chunks.push(`export interface ${interfaceName} {`);
      const props = ((schema as Record<string, unknown>).properties ?? {}) as Record<string, unknown>;
      const required = ((schema as Record<string, unknown>).required as string[] | undefined) ?? [];
      if (Object.keys(props).length === 0) {
        chunks.push(`  [key: string]: unknown;`);
      }
      for (const [propName, propSchema] of Object.entries(props)) {
        const key = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(propName) ? propName : JSON.stringify(propName);
        const isRequired = required.includes(propName);
        const typeStr = tsTypeFor(propSchema as Record<string, unknown>, seen);
        chunks.push(`  readonly ${key}${isRequired ? '' : '?'}: ${typeStr};`);
      }
      chunks.push('}', '');
    } else {
      chunks.push(`export type ${interfaceName} = ${tsTypeFor(schema as Record<string, unknown>, seen)};`, '');
    }
  }
  return chunks.join('\n');
}

function main(): void {
  const document = JSON.parse(readFileSync(schemaPath, 'utf8')) as Record<string, unknown>;
  const outDir = resolve(root, 'src/generated');
  mkdirSync(outDir, { recursive: true });
  const contracts = generateSchemaInterfaces(document);
  writeFileSync(resolve(outDir, 'opencode-contracts.ts'), contracts);
  console.log(
    `Generated ${(document.components as Record<string, unknown> | undefined)?.schemas ? Object.keys((document.components as Record<string, unknown>).schemas as Record<string, unknown>).length : 0} schema contracts → src/generated/opencode-contracts.ts`,
  );
}

main();
