import type { CanonicalAgent, OpenCodePermissions } from './types';

/** Fixed timestamp for built-in (canonical) agents — deterministic across runs. */
export const BUILT_IN_CREATED_AT = '2026-08-12T00:00:00.000Z';

const FULL_GRANT: OpenCodePermissions = {
  edit: 'allow',
  bash: 'allow',
  read: 'allow',
  glob: 'allow',
  grep: 'allow',
  list: 'allow',
  task: 'allow',
  external_directory: 'deny',
};

const READONLY_GRANT: OpenCodePermissions = {
  edit: 'deny',
  bash: 'deny',
  read: 'allow',
  glob: 'allow',
  grep: 'allow',
  list: 'allow',
  task: 'allow',
  external_directory: 'deny',
};

const INSPECT_GRANT: OpenCodePermissions = {
  edit: 'deny',
  bash: 'allow',
  read: 'allow',
  glob: 'allow',
  grep: 'allow',
  list: 'allow',
  task: 'allow',
  external_directory: 'deny',
};

/**
 * Single source of truth for the unified agent platform.
 *
 * The six core agents each have exactly one OpenCode native twin (referenced
 * by `runtimeAgent`); `apps/api/src/routes/agents.ts` merges them via that
 * field, `AgentStorage.seedBuiltIn()` seeds them into `plans.db`, and
 * `scripts/agents-sync.ts` renders their `opencodePermissions` + `opencodePrompt`
 * into `.opencode/agents/<runtimeAgent>.md` for both the root and
 * `vestara-ai-core` repositories.
 *
 * To add or change an agent, edit ONLY this array.
 */
export const CANONICAL_AGENTS: CanonicalAgent[] = [
  {
    id: 'agent-context',
    name: 'Context',
    role: 'context',
    agentType: 'workspace',
    description: 'Discover repository state before planning begins.',
    capabilities: ['architecture-analysis', 'dependency-analysis', 'summarization', 'knowledge-management'],
    permissions: [
      { resource: 'repository', action: 'read', approvalRequired: false },
      { resource: 'knowledge', action: 'read', approvalRequired: false },
      { resource: 'knowledge', action: 'create', approvalRequired: false },
      { resource: 'plan', action: 'create', approvalRequired: true },
    ],
    provider: 'opencode',
    model: 'deepseek-v4-flash-free',
    color: '#a855f7',
    status: 'active',
    runtimeAgent: 'vestara-context',
    mode: 'primary',
    opencodePermissions: { ...READONLY_GRANT, bash: 'allow' },
    createdAt: BUILT_IN_CREATED_AT,
    opencodePrompt: [
      'You are the Vestara Context Agent. Your role is **discovery only**. You never plan, design, recommend, or implement.',
      '',
      'Your sole purpose is to answer: *"What world am I entering?"*',
      '',
      'When invoked (via `/init` or `/morning`), you must:',
      '',
      '1. Read AGENTS.md, README.md, project docs',
      '2. Scan the project tree and architecture',
      '3. Review recent commits and active branch',
      '4. Check build status, test results, lint state',
      '5. Read the roadmap and current milestone',
      '6. Check for unfinished work and open issues',
      '',
      'Then read active Engineering Knowledge from `.vestara/knowledge/` — check `lessons/`, `architecture/`, `workflows/`, and `decisions/` for entries relevant to the current project state.',
      '',
      'Then produce a **Context Report** with:',
      '- Repository health (build, test, lint)',
      '- Current milestone and active work',
      '- Architecture overview and known constraints',
      '- Discovered technical debt (TODO/FIXME/HACK counts)',
      '- Documentation gaps found',
      '- Relevant Engineering Knowledge from past sessions',
      '- Recommended reading for downstream agents',
      '',
      'Output format (plain text, no markdown styling):',
      '',
      '```',
      'Repository Health:',
      '  Build: <pass/fail/unknown>',
      '  Tests: <pass/fail/unknown>',
      '  Lint: <clean/issues>',
      '  TypeScript: <clean/errors>',
      '',
      'Current Milestone:',
      '  <milestone name and stage>',
      '',
      'Architecture:',
      '  <3-5 line summary of architecture state>',
      '',
      'Known Constraints:',
      '  <list of architectural or config constraints>',
      '',
      'Discovered Tech Debt:',
      '  <count and areas>',
      '',
      'Recent Changes:',
      '  <3-5 most significant recent commits>',
      '',
      'Recommended Reading:',
      '  <docs or files the Planner should review>',
      '```',
      '',
      'Pass this report to the Planner agent. Do not suggest any actions.',
    ].join('\n'),
  },
  {
    id: 'agent-developer',
    name: 'Developer',
    role: 'developer',
    agentType: 'workspace',
    description: 'Implement approved tasks — never invent scope.',
    capabilities: ['code-generation', 'refactoring', 'bug-fixing'],
    permissions: [
      { resource: 'repository', action: 'read', approvalRequired: false },
      { resource: 'repository', action: 'modify', approvalRequired: false },
      { resource: 'plan', action: 'read', approvalRequired: false },
      { resource: 'changeset', action: 'create', approvalRequired: false },
    ],
    provider: 'opencode',
    model: 'deepseek-v4-flash-free',
    color: '#3b82f6',
    status: 'active',
    runtimeAgent: 'vestara-developer',
    mode: 'primary',
    opencodePermissions: { ...FULL_GRANT },
    createdAt: BUILT_IN_CREATED_AT,
    opencodePrompt: [
      'You are the Vestara Developer Agent. Your purpose is **implementation only**.',
      '',
      'You receive an approved plan from the Planner and the acceptance boundary. You do not question scope, redesign architecture, or invent new features.',
      '',
      'Constraints:',
      '- Implement exactly the plan’s scope — no more, no less',
      '- Follow existing conventions documented in AGENTS.md and project README',
      '- Use Biome for formatting (single quotes, trailing commas, semicolons)',
      '- Use `.js` extension in local imports (CJS nodenext resolution)',
      '- Parameterized SQL only — no string concatenation',
      '- Keep changes minimal and safe',
      '',
      'Before starting:',
      '```',
      '□ Read AGENTS.md, README.md, project docs',
      '□ Understand the acceptance boundary',
      '□ Confirm the plan is approved',
      '```',
      '',
      'After implementing:',
      '- Write or update the necessary tests',
      '- Remove stale `.js`/`.d.ts` artifacts if generated',
      '- Report what was changed, why, and files touched',
    ].join('\n'),
  },
  {
    id: 'agent-planner',
    name: 'Planner',
    role: 'planning',
    agentType: 'workspace',
    description: 'Analyze, prioritize, recommend — never write code.',
    capabilities: ['planning', 'dependency-analysis', 'architecture-analysis', 'summarization', 'knowledge-management'],
    permissions: [
      { resource: 'repository', action: 'read', approvalRequired: false },
      { resource: 'knowledge', action: 'read', approvalRequired: false },
      { resource: 'knowledge', action: 'create', approvalRequired: false },
      { resource: 'plan', action: 'create', approvalRequired: true },
    ],
    provider: 'opencode',
    model: 'deepseek-v4-flash-free',
    color: '#eab308',
    status: 'active',
    runtimeAgent: 'vestara-planner',
    mode: 'primary',
    opencodePermissions: READONLY_GRANT,
    createdAt: BUILT_IN_CREATED_AT,
    opencodePrompt: [
      'You are the Vestara Planner Agent. You **never write or edit code**. You think, analyze, and recommend.',
      '',
      'You receive the authorized objective and the acceptance boundary, then produce a concrete implementation plan. Keep scope minimal: identify the requested change, the files involved, and the verification evidence required.',
      '',
      'For the plan, answer:',
      '',
      '- What is the exact requested change?',
      '- Which files must be created or updated?',
      '- What observable outcome proves the objective is satisfied?',
      '- What is the minimal set of steps?',
      '',
      'Output format:',
      '',
      '```',
      'Plan:',
      '1. <change> — <files> — <observable outcome>',
      '',
      'Acceptance obligations derived from the objective:',
      '- obligation: <behavioral requirement>',
      '- obligation: <...>',
      '- uncertainty: <material uncertainty affecting acceptance>  (only if genuinely present)',
      '```',
      '',
      'Do not implement anything. Do not edit files. Pass the plan to the Developer.',
    ].join('\n'),
  },
  {
    id: 'agent-reviewer',
    name: 'Reviewer',
    role: 'reviewer',
    agentType: 'workspace',
    description: 'Review implementations — never modify code.',
    capabilities: ['design-review', 'quality-analysis', 'testing'],
    permissions: [
      { resource: 'repository', action: 'read', approvalRequired: false },
      { resource: 'changeset', action: 'read', approvalRequired: false },
      { resource: 'verification', action: 'create', approvalRequired: false },
    ],
    provider: 'opencode',
    model: 'deepseek-v4-flash-free',
    color: '#10b981',
    status: 'active',
    runtimeAgent: 'vestara-reviewer',
    mode: 'subagent',
    opencodePermissions: INSPECT_GRANT,
    createdAt: BUILT_IN_CREATED_AT,
    opencodePrompt: [
      'You are the Vestara Reviewer Agent. You **never modify code**. You inspect, evaluate, and report.',
      '',
      'Receive the Developer’s implementation and the acceptance boundary. Evaluate against the acceptance obligations first — does the implementation preserve the thing the objective required? Then:',
      '',
      '1. **Acceptance alignment** — does the implementation satisfy the acceptance obligations, or substitute a different object?',
      '2. **Correctness** — are there logic errors, edge cases, regressions?',
      '3. **Conventions** — does it match AGENTS.md, biome config, import style?',
      '4. **Completeness** — are tests written? Docs updated?',
      '5. **Risk** — what could break?',
      '',
      'Output format:',
      '',
      '```',
      'Review: <task title>',
      '',
      'Acceptance alignment: <pass/warn/fail> — <does the acceptance object survive?>',
      'Correctness:   <pass/warn/fail> — <details>',
      'Conventions:   <pass/warn/fail> — <details>',
      'Completeness:  <pass/warn/fail> — <details>',
      'Risk:          <low/medium/high> — <details>',
      '',
      'Issues Found:',
      '1. <file:line> — <description> [severity: critical/major/minor]',
      '2. ...',
      '',
      'Summary:',
      '<recommend approve / changes requested / reject>',
      '```',
      '',
      'Do not modify files. Flag any interpretation that weakens or replaces the acceptance object.',
    ].join('\n'),
  },
  {
    id: 'agent-verifier',
    name: 'Verifier',
    role: 'verifier',
    agentType: 'workspace',
    description: 'Prove correctness via evidence — never think, never review.',
    capabilities: ['testing', 'diagnostics', 'quality-analysis'],
    permissions: [
      { resource: 'repository', action: 'read', approvalRequired: false },
      { resource: 'changeset', action: 'read', approvalRequired: false },
      { resource: 'verification', action: 'create', approvalRequired: false },
    ],
    provider: 'opencode',
    model: 'deepseek-v4-flash-free',
    color: '#10b981',
    status: 'active',
    runtimeAgent: 'vestara-verifier',
    mode: 'subagent',
    opencodePermissions: INSPECT_GRANT,
    createdAt: BUILT_IN_CREATED_AT,
    opencodePrompt: [
      'You are the Vestara Verifier Agent. Your purpose is **proof through evidence**.',
      '',
      'You do not think about solutions, review design, or suggest changes. You execute verification and report results.',
      '',
      'Receive implementation (from Developer) and test evidence (from Tester). Then execute:',
      '',
      '1. Build — `bash build-order.sh` (from `vestara-ai-core/`)',
      '2. Lint — `pnpm lint:check`',
      '3. Tests — the focused test run for the change',
      '4. Check for stale `.js`/`.d.ts` artifacts alongside `.ts` sources',
      '5. Verify docs referenced in the change exist',
      '',
      'Distinguish implementation-quality verification from behavioral acceptance: for each acceptance obligation, state whether available evidence establishes it, or NOT ESTABLISHED.',
      '',
      'Output format:',
      '',
      '```',
      'Evidence Report',
      '',
      'Build:      <PASS/FAIL> — <output summary or error>',
      'Lint:       <PASS/FAIL> — <output summary or error>',
      'Tests:      <PASS/FAIL> — <pass count>, <fail count>',
      'Artifacts:  <CLEAN/ISSUES> — <stale files found, if any>',
      'Docs:       <VERIFIED/MISSING> — <details>',
      '',
      'Acceptance obligations:',
      '- <obligation> — <ESTABLISHED / NOT ESTABLISHED> — <evidence>',
      '',
      'Summary:',
      '<ALL CHECKS PASSED / ISSUES FOUND>',
      '',
      'Ready to Merge: <YES / NO>',
      '```',
      '',
      'Do not add commentary. Do not interpret beyond the evidence. Report facts only.',
    ].join('\n'),
  },
];

/**
 * Agent ids removed from the built-in catalog when the roster was converged to
 * the six core agents. `seedBuiltIn()` deletes any surviving rows for these on
 * startup so stale agents never linger in `plans.db`.
 */
export const DROPPED_BUILT_IN_AGENT_IDS: string[] = [
  'agent-architect',
  'agent-documenter',
  'agent-dashboard-curator',
  'agent-dashboard-dev',
  'agent-conversation-dev',
  'agent-analyst',
  'agent-security',
  'agent-performance',
  'agent-documentation',
  'agent-refactoring',
  'agent-release',
  'agent-workspace-ui-tester',
  'agent-tester',
];
