/**
 * Execution artifact boundary.
 *
 * Minimal generic representation for execution-produced artifacts.
 * References large payloads rather than embedding them.
 *
 * CORE-003 Phase 10: Determine only whether the execution contract needs
 * artifact identity, type, reference, and metadata. Do not design renderers.
 */

/**
 * Types of artifacts an execution can produce.
 */
export type ArtifactKind =
  | 'file-change' // A file was created, modified, or deleted
  | 'diff' // A diff/patch representation
  | 'shell-output' // Output from a shell command
  | 'generated-file' // A file generated by the execution
  | 'test-result' // Test execution results
  | 'verification-evidence' // Evidence used for verification
  | 'image' // An image or screenshot
  | 'document' // A document (markdown, etc.)
  | 'todo-snapshot' // Snapshot of task/todo state
  | 'other'; // Unclassified artifact

/**
 * A reference to an artifact produced by an execution.
 *
 * INVARIANT: Artifacts use references, not embedded payloads.
 * The actual content lives outside the execution contract
 * (in the filesystem, evidence store, or runtime).
 */
export interface ExecutionArtifact {
  /** Unique identifier for this artifact. */
  readonly id: string;

  /** What type of artifact this is. */
  readonly kind: ArtifactKind;

  /** Reference to the artifact content (URI, path, or content hash). */
  readonly reference: string;

  /** Human-readable description. */
  readonly summary?: string;

  /** Artifact-specific metadata. */
  readonly metadata?: Record<string, unknown>;
}

/**
 * Types of evidence an execution can produce.
 */
export type EvidenceKind =
  | 'command' // Shell command execution
  | 'file' // File system operation
  | 'test' // Test execution
  | 'log' // Log output
  | 'screenshot' // Visual evidence
  | 'api' // API call evidence
  | 'environment' // Environment state
  | 'custom'; // Custom evidence type

/**
 * Evidence collected during execution.
 *
 * Evidence is distinct from artifacts:
 *   - Artifacts are PRODUCED by the execution (outputs)
 *   - Evidence is COLLECTED during execution (proof of what happened)
 */
export interface ExecutionEvidence {
  /** Unique identifier for this evidence. */
  readonly id: string;

  /** What type of evidence this is. */
  readonly kind: EvidenceKind;

  /** Human-readable summary of the evidence. */
  readonly summary: string;

  /** Reference to the evidence content. */
  readonly reference?: string;

  /** Evidence-specific metadata. */
  readonly metadata?: Record<string, unknown>;
}
